services:
  ea-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: externalbrain-cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${EA_CF_TUNNEL_TOKEN}
    networks:
      - default
      - property_default

networks:
  property_default:
    external: true
    name: property_default
